create database FEATURE_DEPLOYER;

GRANT ALL PRIVILEGES ON FEATURE_DEPLOYER.* TO 'root'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;


CREATE TABLE BASH_PROCESS (
	PID DECIMAL(10) NOT NULL,
	PROCESS_NAME VARCHAR(100) NOT NULL,
	PROCESS_DESCRIPTION VARCHAR(100) NOT NULL,
	TYPE_DESCRIPTION VARCHAR(100) NOT NULL,
	ASSOCIATED_PID DECIMAL(10) NOT NULL,
	ASSOCIATED_PROCESS_NAME VARCHAR(100) NOT NULL
);


CREATE TABLE DEFINED_FRONT_PROJECT (
	PROJECT_NAME VARCHAR(100) NOT NULL,
	PROJECT_DESCRIPTION VARCHAR(100) NOT NULL
);


CREATE TABLE CURRENT_FRONT_DEPLOY (
	PID_BASH_PROCESS DECIMAL(10) NOT NULL,
	PROJECT_NAME VARCHAR(100) NOT NULL,
	PROJECT_DESCRIPTION VARCHAR(100) NOT NULL,
	SERVER_PORT DECIMAL(10) NOT NULL
);